project:
  type: website

website:
  title: "Single-cell analysis tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorials/00-setup/index.qmd
        text: "00: Setup"
      - href: tutorials/01-read-h5ad/index.qmd
        text: "01: Read H5AD"
      - href: tutorials/02-preprocessing/index.qmd
        text: "02: Preprocessing"
      - href: tutorials/03a-pseudobulk/index.qmd
        text: "03a: Pseudobulk generation"
      - href: tutorials/03b-trajectory/index.qmd
        text: "03b: Trajectory"
      - href: tutorials/04-pseudobulk-de/index.qmd
        text: "04: Pseudobulk DE"

format:
  html:
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
