project:
  type: website

website:
  title: "Single-cell analysis tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorials/00-setup/index.qmd
        text: "00: Setup"
      - href: tutorials/01-read-h5ad/index.qmd
        text: "01: Read H5AD"
      - href: tutorials/02-preprocessing/index.qmd
        text: "02: Preprocessing"

format:
  html:
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
